---
version: '3'
services:
  jenkins_master:
    image: individuwill/jenkins-docker
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_master_vol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_master_vol:
    driver_opts:
      type: none
      device: $PWD/jenkins_master_vol
      o: bind

